version: 0.2
env:
  variables:
    DIST_FOLDER: "dist"
    BUILD_ENV: "dev"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Install dependencies"
      - npm install -g aws-cdk
      - npm install -g typescript
      - cdk bootstrap
      - cdk --version
  build:
    commands:
      - npm install
      - 'npm run cdk synth -o -v --all --requier-approval=never'
      - aws s3 cp AwesomeServerlessApiStack.template.json s3://$SAM_BUCKET
      - |-
        echo "{ \"Parameters\" : { \"MasterSecretArn\" : \"$SECRET_ARN_DEV\", \"MasterSecretsManagerKey\" : \"$SECRET_MANAGER_KEY\", \"Stage\" : \"dev\" } }" > sample-configuration-dev.json
        echo "{ \"Parameters\" : { \"MasterSecretArn\" : \"$SECRET_ARN_PROD\", \"MasterSecretsManagerKey\" : \"$SECRET_MANAGER_KEY\", \"Stage\" : \"prod\" } }" > sample-configuration-prod.json
artifacts:
  files:
    - AwesomeServerlessApiStack.template.json
    - sample-configuration-dev.json
    - sample-configuration-prod.json